apiVersion: v2
description: Intershop Commerce Management - ICM Test Chart
name: icm-test
version: 1.2.0
annotations:
  requestedMemoryQuota: 6000Mi
  requestedCpuQuotaInMinutes: "2200"
dependencies:
  - name: icm
    version: 2.18.0
    repository: file://../icm
