apiVersion: v2
description: Intershop Commerce Management - ICM Test Chart
name: icm-test
version: 1.0.0-alpha
annotations:
  requestedMemoryQuota: 6000Mi
  requestedCpuQuotaInMinutes: "2200"
dependencies:
  - name: icm
    version: 2.17.0-alpha
    repository: file://../icm
