[tool.bumpversion]
current_version = "1.2.1"

[[tool.bumpversion.files]]
filename = "Chart.yaml"
search = "name: icm-replication-test\nversion: {current_version}"
replace = "name: icm-replication-test\nversion: {new_version}"
