apiVersion: v2
appVersion: "13.1.2"
description: Intershop Commerce Management - ICM Replication Test Chart
# name and version must be in this exact order, otherwise bump2version won't work
name: icm-replication-test
version: 1.2.1
annotations:
  requestedMemoryQuota: 9Gi
  requestedCpuQuotaInMinutes: 3000
dependencies:
  - name: icm-test
    version: 1.2.1
    repository: file://../icm-test
    alias: icm-live
  - name: icm-test
    version: 1.2.1
    repository: file://../icm-test
    alias: icm-edit
