[tool.bumpversion]
current_version = "1.0.2"

[[tool.bumpversion.files]]
filename = "Chart.yaml"
search = "name: icm-job-test\nversion: {current_version}"
replace = "name: icm-job-test\nversion: {new_version}"
