apiVersion: v2
description: Intershop Commerce Management - ICM Job Server Test Chart
# name and version must be in this exact order, otherwise bump2version won't work
name: icm-job-test
version: 1.3.0-alpha
annotations:
  requestedMemoryQuota: 8000Mi
  requestedCpuQuotaInMinutes: "2200"
dependencies:
  - name: icm-test
    version: 1.0.0-alpha
    repository: file://../icm-test

