{{- if .Values.cache.reset.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cache-reset
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-cache-reset
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [apps]
    resources: [deployments]
    resourceNames: [{{ include "pwa-cache.fullname" . }}]
    verbs: [get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-cache-reset
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-cache-reset
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cache-reset
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job-cache-reset
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-cache-reset
      containers:
        - name: kubectl
          image: {{ default "ishcp.azurecr.io/ishops/cronjob-utils:1.0.0" .Values.cache.reset.image }}
          command:
            [
              "bash",
              "-c",
              "kubectl rollout restart deployment/{{ include "pwa-cache.fullname" . }}",
            ]
{{- end -}}
