[tool.bumpversion]
current_version = "2.7.0-alpha"

[[tool.bumpversion.files]]
filename = "Chart.yaml"
search = "name: icm-replication\nversion: {current_version}"
replace = "name: icm-replication\nversion: {new_version}"
