apiVersion: v2
name: icm-as
description: Intershop Commerce Management - AppServer
type: application
version: 1.2.6-alpha
appVersion: 11.2.0
dependencies:
- name: icm-job
  version: 1.0.1
  repository: file://../icm-job
  condition: job.enabled
