apiVersion: v2
# name and version must be in this exact order, otherwise bump2version won't work
name: icm-as
version: 2.12.0
description: Intershop Commerce Management - AppServer
type: application
appVersion: 11.10.3-LTS

dependencies:
  - name: ingress-nginx
    version: 4.11.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
