apiVersion: v2
name: pwa-main
version: 0.6.0
description: Helm Chart to operate Intershop Progressive Web App
type: application
dependencies:
  - name: icm
    version: 0.5.0
    repository: https://intershop.github.io/helm-charts
    condition: hybrid.enabled
