dependencies:
  - name: icm-as
    version: 0.8.1
    repository: file://../icm-as
  - name: icm-web
    version: 0.7.3
    repository: file://../icm-web
  - name: mailhog
    version: 5.2.0
    repository: https://codecentric.github.io/helm-charts
    condition: mailhog.enabled
