name: "Lint and test icm charts"
on:
  pull_request:
    paths: 
    - 'charts/icm-as/**'
    - 'charts/icm-web/**'
    - 'charts/icm/**'
    - 'charts/icm-replication/**'

jobs:
  lint-test-icm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct_icm.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ct_icm.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: kind.yaml
        if: steps.list-changed.outputs.changed == 'true'
        
      - name: Run chart-testing (install)
        run: |
          random_value=`tr -dc 'a-z0-9' < /dev/urandom | head -c10`
          kubectl create namespace ct-icm-$random_value
          
          kubectl create secret docker-registry dockerhub --namespace=ct-icm-$random_value --docker-username=${{ secrets.DOCKER_USERNAME }} --docker-password=${{ secrets.DOCKER_PASSWORD }} --docker-email=eng-ateam@intershop.com
          
          mkdir -p /tmp/sites
          mkdir -p /tmp/pagecache
          mkdir -p /tmp/icm/sites
          mkdir -p /tmp/icm/pagecache
          mkdir -p /tmp/icm-live/sites
          mkdir -p /tmp/icm-live/pagecache
          mkdir -p /tmp/icm-edit/sites
          mkdir -p /tmp/icm-edit/pagecache
          
          sed -i 's/<local folder>/\/tmp\/sites/' charts/icm-as/values.yaml
          sed -i 's/<local folder>/\/tmp\/pagecache/' charts/icm-web/values.yaml
          sed -i 's/<local sites folder>/\/tmp\/icm\/sites/' charts/icm/values.yaml
          sed -i 's/<local pagecache folder>/\/tmp\/icm\/pagecache/' charts/icm/values.yaml
          sed -i 's/<local sites live folder>/\/tmp\/icm-live\/sites/' charts/icm-replication/values.yaml
          sed -i 's/<local pagecache live folder>/\/tmp\/icm-live\/pagecache/' charts/icm-replication/values.yaml
          sed -i 's/<local sites edit folder>/\/tmp\/icm-edit\/sites/' charts/icm-replication/values.yaml
          sed -i 's/<local pagecache edit folder>/\/tmp\/icm-edit\/pagecache/' charts/icm-replication/values.yaml
          
          sed -i 's/<your license>/${{ secrets.ICM_LICENSE }}/' charts/icm-as/values.yaml
          sed -i 's/<your license>/${{ secrets.ICM_LICENSE }}/' charts/icm/values.yaml
          sed -i 's/<your license>/${{ secrets.ICM_LICENSE }}/' charts/icm-replication/values.yaml
          
          ct install --namespace=ct-icm-$random_value --config ct_icm.yaml
        if: steps.list-changed.outputs.changed == 'true'

