name: "Lint and test icm-as charts"
on:
  pull_request:
    paths:
    - 'charts/icm-as/**'

jobs:
  lint-test-icm-as:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.2

      - name: Install Helm Unittest
        run: |
          helm plugin install https://github.com/quintush/helm-unittest --version=v0.2.8

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct_icm-as.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ct_icm-as.yaml

      - name: Run Helm Unittest
        run: |
          helm unittest --helm3  --output-file charts/icm-as/tests/__results__/junit.xml --output-type JUnit charts/icm-as

      - name: Publish Helm Unittest Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: charts/icm-as/tests/__results__/*.xml

      - name: Run Helm Unittest
        run: |
          helm unittest --helm3  --output-file charts/icm-as/tests/__results__/junit.xml --output-type JUnit charts/icm-as

      - name: Publish Helm Unittest Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: charts/icm-as/tests/__results__/*.xml

      - name: Run Helm Unittest
        run: |
          helm unittest --helm3  --output-file charts/icm-as/tests/__results__/junit.xml --output-type JUnit charts/icm-as

      - name: Publish Helm Unittest Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: charts/icm-as/tests/__results__/*.xml

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        with:
          config: kind.yaml
        if: steps.list-changed.outputs.changed == 'true'

      - name: Log into registry docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: |
          set -x
          random_value=`tr -dc 'a-z0-9' < /dev/urandom | head -c10`
          export NAMESPACE=ct-icm-as-$random_value
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV

          kubectl create namespace $NAMESPACE

          kubectl create secret docker-registry dockerhub --namespace=$NAMESPACE --docker-username=${{ secrets.DOCKER_USERNAME }} --docker-password=${{ secrets.DOCKER_PASSWORD }} --docker-email=eng-ateam@intershop.com

          mkdir -p /tmp/icm/sites

          sed -i 's/<local folder>/\/tmp\/icm\/sites/' charts/icm-as/values.yaml

          license=$(cat << EOF
          ${{ secrets.ICM_LICENSE }}
          EOF
          )
          sed -i "s[<your license>[${license//$'\n'/}[" charts/icm-as/values.yaml

          docker run -d -p 1433:1433 --name mssql-intershop --env ACCEPT_EULA=Y --env SA_PASSWORD=1nstershop5A --env ICM_DB_NAME=intershop --env ICM_DB_USER=intershop --env ICM_DB_PASSWORD=intershop intershophub/mssql-intershop:2019-1.0
          ipaddress=`ip route | grep -Po '(?<=src )[^ ]+' | head -n 1`
          sed -i "s/<ipaddress or hostname>/$ipaddress/" charts/icm-as/values.yaml

          ct install --namespace=$NAMESPACE --config ct_icm-as.yaml
        if: steps.list-changed.outputs.changed == 'true'
      - name: Debug failure
        if: failure() && steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl describe node -A
          kubectl describe pod -A
          kubectl describe service -A
          kubectl describe daemonset -A
          kubectl logs $(kubectl get pods -n $NAMESPACE -o jsonpath="{.items[0].metadata.name}")
